# Generated by Django 6.0.3 on 2026-04-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_delivery_charge_order_status_order_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.CharField(default='Outside Dhaka', max_length=50, verbose_name='ডেলিভারি জোন'),
        ),
    ]
