# Generated by Django 6.0.3 on 2026-04-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_delivery_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='শিরোনাম')),
                ('content', models.TextField(verbose_name='বিষয়বস্তু')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='ছবি')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
            ],
        ),
    ]
