# Generated by Django 6.0.3 on 2026-04-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='নাম')),
                ('phone', models.CharField(max_length=20, verbose_name='ফোন নম্বর')),
                ('message', models.TextField(verbose_name='বার্তা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='পাঠানোর সময়')),
            ],
        ),
    ]
