# Generated by Django 5.2.11 on 2026-04-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=100, verbose_name='স্টক পরিমাণ'),
        ),
    ]
