# Generated by Django 5.2.11 on 2026-04-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quality_tag',
            field=models.CharField(choices=[('None', 'None'), ('Tested', 'পরিক্ষিত'), ('Best', 'সেরা বীজ'), ('Uncommon', 'আনকমন')], default='None', max_length=20, verbose_name='মান ট্যাগ'),
        ),
    ]
