# Generated by Django 5.2.11 on 2026-04-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_quality_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Special', 'সেরা বীজ'), ('Uncommon', 'আনকমন'), ('Offer', 'অফার'), ('Tested', 'পরিক্ষিত'), ('New', 'নতুন পণ্য')], max_length=50, unique=True, verbose_name='ট্যাগের নাম')),
                ('color', models.CharField(default='bg-gold', max_length=50, verbose_name='ব্যাকগ্রাউন্ড ক্লাস')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='quality_tag',
        ),
        migrations.AddField(
            model_name='product',
            name='product_tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='api.tag', verbose_name='ট্যাগসমূহ'),
        ),
    ]
