# Generated by Django 5.2.11 on 2026-04-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tag_remove_product_quality_tag_product_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cashback_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ক্যাশব্যাক (৳)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('Special', 'সেরা পণ্য'), ('Uncommon', 'আনকমন'), ('Offer', 'অফার'), ('Tested', 'পরিক্ষিত'), ('Popular', 'পপুলার'), ('TwelveMonth', '১২ মাস'), ('New', 'নতুন পণ্য')], max_length=50, unique=True, verbose_name='ট্যাগের নাম'),
        ),
    ]
